plugins {
	id("java")
}

dependencies {
	implementation(project(":platform"))

	// Vanilla 26.2 dependency set, generated from the official version JSON
	// (https://piston-meta.mojang.com/v1/packages/73300f962b1d9c183957806be67850b740d3c949/26.2.json)
	implementation("at.yawk.lz4:lz4-java:1.10.1")
	implementation("com.azure:azure-json:1.4.0")
	implementation("com.github.oshi:oshi-core:6.9.0")
	implementation("com.google.code.gson:gson:2.14.0")
	implementation("com.google.guava:failureaccess:1.0.3")
	implementation("com.google.guava:guava:33.6.0-jre")
	implementation("com.ibm.icu:icu4j:78.3")
	implementation("com.microsoft.azure:msal4j:1.24.1")
	implementation("com.mojang:authlib:9.0.75")
	implementation("com.mojang:blocklist:1.0.10")
	implementation("com.mojang:brigadier:1.3.10")
	implementation("com.mojang:datafixerupper:10.0.21")
	implementation("com.mojang:jtracy:1.0.37")
	implementation("com.mojang:logging:1.7.12")
	implementation("com.mojang:patchy:2.2.10")
	implementation("com.mojang:text2speech:1.19.12")
	implementation("commons-codec:commons-codec:1.22.0")
	implementation("commons-io:commons-io:2.20.0")
	implementation("io.netty:netty-buffer:4.2.15.Final")
	implementation("io.netty:netty-codec-base:4.2.15.Final")
	implementation("io.netty:netty-codec-compression:4.2.15.Final")
	implementation("io.netty:netty-codec-http:4.2.15.Final")
	implementation("io.netty:netty-common:4.2.15.Final")
	implementation("io.netty:netty-handler:4.2.15.Final")
	implementation("io.netty:netty-resolver:4.2.15.Final")
	implementation("io.netty:netty-transport-classes-epoll:4.2.15.Final")
	implementation("io.netty:netty-transport-classes-kqueue:4.2.15.Final")
	implementation("io.netty:netty-transport-native-epoll:4.2.15.Final:linux-x86_64")
	implementation("io.netty:netty-transport-native-unix-common:4.2.15.Final")
	implementation("io.netty:netty-transport:4.2.15.Final")
	implementation("it.unimi.dsi:fastutil:8.5.18")
	implementation("net.java.dev.jna:jna-platform:5.17.0")
	implementation("net.java.dev.jna:jna:5.17.0")
	implementation("net.sf.jopt-simple:jopt-simple:5.0.4")
	implementation("org.apache.commons:commons-compress:1.28.0")
	implementation("org.apache.commons:commons-lang3:3.20.0")
	implementation("org.apache.logging.log4j:log4j-api:2.26.0")
	implementation("org.apache.logging.log4j:log4j-core:2.26.0")
	implementation("org.apache.logging.log4j:log4j-slf4j2-impl:2.26.0")
	implementation("org.jcraft:jorbis:0.0.17")
	implementation("org.joml:joml:1.10.8")
	implementation("org.jspecify:jspecify:1.0.0")
	implementation("org.slf4j:slf4j-api:2.0.17")

	// Compile-time only: referenced by decompiled sources, not shipped at runtime
	compileOnly("org.jetbrains:annotations:26.0.2")
	compileOnly("org.teavm:teavm-interop:0.13.1")
	compileOnly("org.teavm:teavm-jso:0.13.1") // Isolated mod bridge only
	compileOnly("org.teavm:teavm-jso-apis:0.13.1") // Isolated mod bridge typed arrays
	compileOnly("ca.weblite:java-objc-bridge:1.1") // MacosUtil (mac-only path)

	// LWJGL 3.4.1 — plain core instead of Mojang's :unsafe classifier variant
	// (same API; swap to :unsafe + transitive excludes if MemoryUtil perf matters)
	implementation("org.lwjgl:lwjgl:3.4.1")
	implementation("org.lwjgl:lwjgl-freetype:3.4.1")
	implementation("org.lwjgl:lwjgl-glfw:3.4.1")
	implementation("org.lwjgl:lwjgl-jemalloc:3.4.1")
	implementation("org.lwjgl:lwjgl-openal:3.4.1")
	implementation("org.lwjgl:lwjgl-opengl:3.4.1")
	implementation("org.lwjgl:lwjgl-shaderc:3.4.1")
	implementation("org.lwjgl:lwjgl-spvc:3.4.1")
	implementation("org.lwjgl:lwjgl-stb:3.4.1")
	implementation("org.lwjgl:lwjgl-tinyfd:3.4.1")
	implementation("org.lwjgl:lwjgl-vma:3.4.1")
	implementation("org.lwjgl:lwjgl-vulkan:3.4.1")

	runtimeOnly("com.mojang:jtracy:1.0.37:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-freetype:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-glfw:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-jemalloc:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-openal:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-opengl:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-shaderc:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-spvc:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-stb:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-tinyfd:3.4.1:natives-linux")
	runtimeOnly("org.lwjgl:lwjgl-vma:3.4.1:natives-linux")
}
