package net.lax1dude.eaglercraft.v1_8.internal;

import org.teavm.jso.JSBody;
import org.teavm.jso.JSByRef;
import org.teavm.jso.typedarrays.Float64Array;

/**
 * WEB impl of the native worldgen-noise seam. Loads a self-contained Rust-to-Wasm kernel,
 * built from the audited source in {@code wasm-toolchain/rustnoise}, that reimplements Minecraft's
 * {@code NormalNoise} as a native f64 routine, and exposes it as a slot-based cache. The
 * point: 26.2's Java noise runs under TeaVM green-thread/coroutine instrumentation (a
 * case/spill per call) which, on the millions of samples per chunk, is the worldgen
 * bottleneck (the 36 s spawn / 53 s server-behind). Direct density-noise fills are packed into
 * one bounded call so TeaVM does not cross the Java/native seam for every sample.
 *
 * <p>The kernel imports NOTHING (instantiated with {@code {}}) and owns a fixed linear-memory
 * arena; all 256 slots and the bounded batch scratch fit without growth, so a cached buffer never detaches. The
 * exact slot layout + arithmetic were validated bit-identical against vanilla in
 * {@code wasm-toolchain/rustnoise/validate.mjs} (maxAbsDiff = 0.0 over 10 configs x 1000
 * points, incl. the 32-octave max, multiple slots, and packed batches). The DESKTOP stub ({@code :platform}) returns
 * {@code available()==false} so shared game code (NormalNoise) never touches this; this
 * FQN shadows the stub on the web classpath (same mechanism as PlatformAudioDecode).</p>
 *
 * <p>Runs in whichever realm builds a NormalNoise: the integrated-server worker (worldgen)
 * and, for client biome noise, the main thread — each gets its own kernel instance in its
 * own {@code globalThis}. NormalNoise still runs a per-instance parity gate before trusting
 * a slot, so any wiring mistake here degrades to the (correct) Java path, never bad terrain.</p>
 */
public final class PlatformNativeNoise {

	// Generated by wasm-toolchain/rustnoise/embed.mjs from rustnoise.wasm.
	private static final String WASM_B64 =
			"AGFzbQEAAAABMQlgBH9/f38AYAJ/fwBgAAF/YAN8fHwBfGAEf3x8fAF8YAF/AGABfAF8YAF/AX9gAAADDw4AAQICAgIDBAUBBgcCCAUDAQA6BgkBfwFBgIDA"
			+ "AAsHjQELBm1lbW9yeQIABmlvX3B0cgACEG1heF9iYXRjaF9wb2ludHMAAwttYXhfb2N0YXZlcwAECW1heF9zbG90cwAFBW5vaXNlAAYKbm9pc2Vfc2xvdAAH"
			+ "C25vaXNlX2JhdGNoAAgQbm9pc2VfYmF0Y2hfc2xvdAAJCHNsb3RfcHRyAAsJc3RhdGVfcHRyAAwKwU4OOQACQAJAIAMgAkkNACADQSFJDQELIAIgAxCBgICA"
			+ "AAALIAAgAyACazYCBCAAIAEgAkGwAmxqNgIACwkAEI2AgIAAAAsIAEGAgMCAAAsGAEGAwAALBABBIAsFAEGAAgsQAEEAIAAgASACEIeAgIAAC8UlBAh/CXwE"
			+ "fwd8I4CAgIAAQRBrIgQkgICAgABBACEFQSAgAEEAIABBAEobIgBB/wEgAEH/AUgbQZjMAGwiACgCkIDMgAAiBkEgIAZBIEkbIgdrIgYgACgClIDMgAAiCCAG"
			+ "IAhJGyEJIAdBsAJsIQogAEGYgMyAAGohCyAAQYCAzIAAaiEARAAAAAAAAAAAIQwCQANAIAogBUYNASAAIAVqIgZBsAJqKwMAIQ0gASAGQbgCaisDACIOoiIP"
			+ "RAAAAAAAAGA+okQAAAAAAADgP6AQioCAgAAhECACIA6iIhFEAAAAAAAAYD6iRAAAAAAAAOA/oBCKgICAACESIAMgDqIiE0QAAAAAAABgPqJEAAAAAAAA4D+g"
			+ "EIqAgIAAIRQgDyAQRAAAAAAAAIBBoqEgBkGYAmorAwCgIQ4gDiAOEIqAgIAA/AIiFbehIQ8gESASRAAAAAAAAIBBoqEgBkGgAmorAwCgIQ4gDiAOEIqAgIAA"
			+ "/AIiFrehIQ4gEyAURAAAAAAAAIBBoqEgBkGoAmorAwCgIRAgECAQEIqAgIAA/AIiCLehIRAgACAFIBYgACAFIBVBAWpB/wFxampBGGotAABqIhdB/wFxampB"
			+ "GGotAAAhGCAAIAUgFiAAIAUgFUH/AXFqakEYai0AAGoiFUEBakH/AXFqakEYaiEWIAAgBSAXQQFqQf8BcWpqQRhqIRcCQAJAAkACQAJAAkACQAJAAkACQAJA"
			+ "AkACQAJAIAAgBSAIIAAgBSAVQf8BcWpqQRhqLQAAaiIVQf8BcWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgDpogEKEhFAwMCyAPIA6hIRQMCwsg"
			+ "D5ogDqEhFAwKCyAPIBCgIRQMCQsgECAPoSEUDAgLIA8gEKEhFAwHCyAPmiAQoSEUDAYLIA4gEKAhFAwFCyAOIBChIRQMBAsgDpogEKEhFAwDCyAPIA6gIRQM"
			+ "AgsgECAOoSEUDAELIA4gD6EhFAsgFi0AACEWIBctAAAhFyAPRAAAAAAAAPC/oCESAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAAIAUgCCAYaiIYQf8B"
			+ "cWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgDpogEKEhGQwMCyASIA6hIRkMCwsgEpogDqEhGQwKCyASIBCgIRkMCQsgECASoSEZDAgLIBIgEKEh"
			+ "GQwHCyASmiAQoSEZDAYLIA4gEKAhGQwFCyAOIBChIRkMBAsgDpogEKEhGQwDCyASIA6gIRkMAgsgECAOoSEZDAELIA4gEqEhGQsgDkQAAAAAAADwv6AhEQJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgACAFIAggFmoiFkH/AXFqakEYai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIBGaIBChIRoMDAsgDyARoSEa"
			+ "DAsLIA+aIBGhIRoMCgsgDyAQoCEaDAkLIBAgD6EhGgwICyAPIBChIRoMBwsgD5ogEKEhGgwGCyARIBCgIRoMBQsgESAQoSEaDAQLIBGaIBChIRoMAwsgDyAR"
			+ "oCEaDAILIBAgEaEhGgwBCyARIA+hIRoLAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAAIAUgCCAXaiIIQf8BcWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcL"
			+ "CAkKCwwACgsgEZogEKEhGwwMCyASIBGhIRsMCwsgEpogEaEhGwwKCyASIBCgIRsMCQsgECASoSEbDAgLIBIgEKEhGwwHCyASmiAQoSEbDAYLIBEgEKAhGwwF"
			+ "CyARIBChIRsMBAsgEZogEKEhGwwDCyASIBGgIRsMAgsgECARoSEbDAELIBEgEqEhGwsgEEQAAAAAAADwv6AhEwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJA"
			+ "AkAgACAFIBVBAWpB/wFxampBGGotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyAOmiAToSEcDAwLIA8gDqEhHAwLCyAPmiAOoSEcDAoLIA8gE6AhHAwJCyAT"
			+ "IA+hIRwMCAsgDyAToSEcDAcLIA+aIBOhIRwMBgsgDiAToCEcDAULIA4gE6EhHAwECyAOmiAToSEcDAMLIA8gDqAhHAwCCyATIA6hIRwMAQsgDiAPoSEcCwJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgACAFIBhBAWpB/wFxampBGGotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyAOmiAToSEdDAwLIBIgDqEhHQwL"
			+ "CyASmiAOoSEdDAoLIBIgE6AhHQwJCyATIBKhIR0MCAsgEiAToSEdDAcLIBKaIBOhIR0MBgsgDiAToCEdDAULIA4gE6EhHQwECyAOmiAToSEdDAMLIBIgDqAh"
			+ "HQwCCyATIA6hIR0MAQsgDiASoSEdCwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgACAFIBZBAWpB/wFxampBGGotAABBD3EOEAoMAQIDBAUGBwsICQoL"
			+ "DAAKCyARmiAToSEeDAwLIA8gEaEhHgwLCyAPmiARoSEeDAoLIA8gE6AhHgwJCyATIA+hIR4MCAsgDyAToSEeDAcLIA+aIBOhIR4MBgsgESAToCEeDAULIBEg"
			+ "E6EhHgwECyARmiAToSEeDAMLIA8gEaAhHgwCCyATIBGhIR4MAQsgESAPoSEeCwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgACAFIAhBAWpB/wFxampB"
			+ "GGotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyARmiAToSERDAwLIBIgEaEhEQwLCyASmiARoSERDAoLIBIgE6AhEQwJCyATIBKhIREMCAsgEiAToSERDAcL"
			+ "IBKaIBOhIREMBgsgESAToCERDAULIBEgE6EhEQwECyARmiAToSERDAMLIBIgEaAhEQwCCyATIBGhIREMAQsgESASoSERCyAMIAZBwAJqKwMAIA0gFCAPIA8g"
			+ "D6KiIA8gD0QAAAAAAAAYQKJEAAAAAAAALsCgokQAAAAAAAAkQKCiIg8gGSAUoaKgIhIgDiAOIA6ioiAOIA5EAAAAAAAAGECiRAAAAAAAAC7AoKJEAAAAAAAA"
			+ "JECgoiIOIBogDyAbIBqhoqAgEqGioCISIBAgECAQoqIgECAQRAAAAAAAABhAokQAAAAAAAAuwKCiRAAAAAAAACRAoKIgHCAPIB0gHKGioCIQIA4gHiAPIBEg"
			+ "HqGioCAQoaKgIBKhoqCioqAhDCAFQbACaiEFDAALCyAEQQhqIAsgByAJIAdqEICAgIAAIAMgACsDCCIOoiEfIAIgDqIhAiABIA6iIQFEAAAAAAAAAAAhDSAE"
			+ "KAIMIQggBCgCCCEFAkADQCAIRQ0BIAVBmAJqKwMAIRkgASAFQaACaisDACIOoiIPRAAAAAAAAGA+okQAAAAAAADgP6AQioCAgAAhECACIA6iIhFEAAAAAAAA"
			+ "YD6iRAAAAAAAAOA/oBCKgICAACESIB8gDqIiE0QAAAAAAABgPqJEAAAAAAAA4D+gEIqAgIAAIRQgDyAQRAAAAAAAAIBBoqEgBUGAAmorAwCgIQ4gDiAOEIqA"
			+ "gIAA/AIiFbehIQ8gESASRAAAAAAAAIBBoqEgBUGIAmorAwCgIQ4gDiAOEIqAgIAA/AIiFrehIQ4gEyAURAAAAAAAAIBBoqEgBUGQAmorAwCgIRAgECAQEIqA"
			+ "gIAA/AIiBrehIRAgBSAWIAUgFUEBakH/AXFqLQAAaiIXQf8BcWotAAAhGCAFIBYgBSAVQf8BcWotAABqIhVBAWpB/wFxaiEWIAUgF0EBakH/AXFqIRcCQAJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAIAUgBiAFIBVB/wFxai0AAGoiFUH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgDpogEKEhFAwMCyAPIA6h"
			+ "IRQMCwsgD5ogDqEhFAwKCyAPIBCgIRQMCQsgECAPoSEUDAgLIA8gEKEhFAwHCyAPmiAQoSEUDAYLIA4gEKAhFAwFCyAOIBChIRQMBAsgDpogEKEhFAwDCyAP"
			+ "IA6gIRQMAgsgECAOoSEUDAELIA4gD6EhFAsgFi0AACEWIBctAAAhFyAPRAAAAAAAAPC/oCESAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAFIAYgGGoi"
			+ "GEH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgDpogEKEhGwwMCyASIA6hIRsMCwsgEpogDqEhGwwKCyASIBCgIRsMCQsgECASoSEbDAgLIBIgEKEh"
			+ "GwwHCyASmiAQoSEbDAYLIA4gEKAhGwwFCyAOIBChIRsMBAsgDpogEKEhGwwDCyASIA6gIRsMAgsgECAOoSEbDAELIA4gEqEhGwsgDkQAAAAAAADwv6AhEQJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgBSAGIBZqIhZB/wFxai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIBGaIBChIRoMDAsgDyARoSEaDAsLIA+a"
			+ "IBGhIRoMCgsgDyAQoCEaDAkLIBAgD6EhGgwICyAPIBChIRoMBwsgD5ogEKEhGgwGCyARIBCgIRoMBQsgESAQoSEaDAQLIBGaIBChIRoMAwsgDyARoCEaDAIL"
			+ "IBAgEaEhGgwBCyARIA+hIRoLAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAFIAYgF2oiBkH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgEZog"
			+ "EKEhHQwMCyASIBGhIR0MCwsgEpogEaEhHQwKCyASIBCgIR0MCQsgECASoSEdDAgLIBIgEKEhHQwHCyASmiAQoSEdDAYLIBEgEKAhHQwFCyARIBChIR0MBAsg"
			+ "EZogEKEhHQwDCyASIBGgIR0MAgsgECARoSEdDAELIBEgEqEhHQsgEEQAAAAAAADwv6AhEwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgBSAVQQFqQf8B"
			+ "cWotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyAOmiAToSEcDAwLIA8gDqEhHAwLCyAPmiAOoSEcDAoLIA8gE6AhHAwJCyATIA+hIRwMCAsgDyAToSEcDAcL"
			+ "IA+aIBOhIRwMBgsgDiAToCEcDAULIA4gE6EhHAwECyAOmiAToSEcDAMLIA8gDqAhHAwCCyATIA6hIRwMAQsgDiAPoSEcCwJAAkACQAJAAkACQAJAAkACQAJA"
			+ "AkACQAJAAkAgBSAYQQFqQf8BcWotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyAOmiAToSEDDAwLIBIgDqEhAwwLCyASmiAOoSEDDAoLIBIgE6AhAwwJCyAT"
			+ "IBKhIQMMCAsgEiAToSEDDAcLIBKaIBOhIQMMBgsgDiAToCEDDAULIA4gE6EhAwwECyAOmiAToSEDDAMLIBIgDqAhAwwCCyATIA6hIQMMAQsgDiASoSEDCwJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgBSAWQQFqQf8BcWotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyARmiAToSEeDAwLIA8gEaEhHgwLCyAPmiAR"
			+ "oSEeDAoLIA8gE6AhHgwJCyATIA+hIR4MCAsgDyAToSEeDAcLIA+aIBOhIR4MBgsgESAToCEeDAULIBEgE6EhHgwECyARmiAToSEeDAMLIA8gEaAhHgwCCyAT"
			+ "IBGhIR4MAQsgESAPoSEeCwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgBSAGQQFqQf8BcWotAABBD3EOEAoMAQIDBAUGBwsICQoLDAAKCyARmiAToSER"
			+ "DAwLIBIgEaEhEQwLCyASmiARoSERDAoLIBIgE6AhEQwJCyATIBKhIREMCAsgEiAToSERDAcLIBKaIBOhIREMBgsgESAToCERDAULIBEgE6EhEQwECyARmiAT"
			+ "oSERDAMLIBIgEaAhEQwCCyATIBGhIREMAQsgESASoSERCyANIAVBqAJqKwMAIBkgFCAPIA8gD6KiIA8gD0QAAAAAAAAYQKJEAAAAAAAALsCgokQAAAAAAAAk"
			+ "QKCiIg8gGyAUoaKgIhIgDiAOIA6ioiAOIA5EAAAAAAAAGECiRAAAAAAAAC7AoKJEAAAAAAAAJECgoiIOIBogDyAdIBqhoqAgEqGioCISIBAgECAQoqIgECAQ"
			+ "RAAAAAAAABhAokQAAAAAAAAuwKCiRAAAAAAAACRAoKIgHCAPIAMgHKGioCIQIA4gHiAPIBEgHqGioCAQoaKgIBKhoqCioqAhDSAIQX9qIQggBUGwAmohBQwA"
			+ "CwsgACsDACEOIARBEGokgICAgAAgDiAMIA2gogsMAEEAIAAQiYCAgAALqCYECH8MfAV/B3wjgICAgABBEGsiAiSAgICAAEEAIQMgAUEAIAFBAEobIgFBgMAA"
			+ "IAFBgMAASBshBCAAQQAgAEEAShsiAUH/ASABQf8BSBtBmMwAbCIBQZiAzIAAaiEFIAFBgIDMgABqIQACQANAIAMgBEYNAUEgIAAoAhAiAUEgIAFBIEkbIgZr"
			+ "IgEgACgCFCIHIAEgB0kbIQggBkGwAmwhCSADQRhsIgFBkIDAgABqKwMAIQogAUGIgMCAAGorAwAhCyABQYCAwIAAaisDACEMRAAAAAAAAAAAIQ1BACEBAkAD"
			+ "QCAJIAFGDQEgACABaiIHQbACaisDACEOIAwgB0G4AmorAwAiD6IiEEQAAAAAAABgPqJEAAAAAAAA4D+gEIqAgIAAIREgCyAPoiISRAAAAAAAAGA+okQAAAAA"
			+ "AADgP6AQioCAgAAhEyAKIA+iIhREAAAAAAAAYD6iRAAAAAAAAOA/oBCKgICAACEVIBAgEUQAAAAAAACAQaKhIAdBmAJqKwMAoCEPIA8gDxCKgICAAPwCIha3"
			+ "oSEQIBIgE0QAAAAAAACAQaKhIAdBoAJqKwMAoCEPIA8gDxCKgICAAPwCIhe3oSEPIBQgFUQAAAAAAACAQaKhIAdBqAJqKwMAoCERIBEgERCKgICAAPwCIhi3"
			+ "oSERIAAgASAXIAAgASAWQQFqQf8BcWpqQRhqLQAAaiIZQf8BcWpqQRhqLQAAIRogACABIBcgACABIBZB/wFxampBGGotAABqIhZBAWpB/wFxampBGGohFyAA"
			+ "IAEgGUEBakH/AXFqakEYaiEZAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCAAIAEgGCAAIAEgFkH/AXFqakEYai0AAGoiFkH/AXFqakEYai0AAEEPcQ4Q"
			+ "CgwBAgMEBQYHCwgJCgsMAAoLIA+aIBGhIRUMDAsgECAPoSEVDAsLIBCaIA+hIRUMCgsgECARoCEVDAkLIBEgEKEhFQwICyAQIBGhIRUMBwsgEJogEaEhFQwG"
			+ "CyAPIBGgIRUMBQsgDyARoSEVDAQLIA+aIBGhIRUMAwsgECAPoCEVDAILIBEgD6EhFQwBCyAPIBChIRULIBctAAAhFyAZLQAAIRkgEEQAAAAAAADwv6AhEwJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgACABIBggGmoiGkH/AXFqakEYai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIA+aIBGhIRsMDAsgEyAPoSEb"
			+ "DAsLIBOaIA+hIRsMCgsgEyARoCEbDAkLIBEgE6EhGwwICyATIBGhIRsMBwsgE5ogEaEhGwwGCyAPIBGgIRsMBQsgDyARoSEbDAQLIA+aIBGhIRsMAwsgEyAP"
			+ "oCEbDAILIBEgD6EhGwwBCyAPIBOhIRsLIA9EAAAAAAAA8L+gIRICQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAAgASAYIBdqIhdB/wFxampBGGotAABB"
			+ "D3EOEAoMAQIDBAUGBwsICQoLDAAKCyASmiARoSEcDAwLIBAgEqEhHAwLCyAQmiASoSEcDAoLIBAgEaAhHAwJCyARIBChIRwMCAsgECARoSEcDAcLIBCaIBGh"
			+ "IRwMBgsgEiARoCEcDAULIBIgEaEhHAwECyASmiARoSEcDAMLIBAgEqAhHAwCCyARIBKhIRwMAQsgEiAQoSEcCwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJA"
			+ "AkAgACABIBggGWoiGEH/AXFqakEYai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIBKaIBGhIR0MDAsgEyASoSEdDAsLIBOaIBKhIR0MCgsgEyARoCEdDAkL"
			+ "IBEgE6EhHQwICyATIBGhIR0MBwsgE5ogEaEhHQwGCyASIBGgIR0MBQsgEiARoSEdDAQLIBKaIBGhIR0MAwsgEyASoCEdDAILIBEgEqEhHQwBCyASIBOhIR0L"
			+ "IBFEAAAAAAAA8L+gIRQCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAAgASAWQQFqQf8BcWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgD5og"
			+ "FKEhHgwMCyAQIA+hIR4MCwsgEJogD6EhHgwKCyAQIBSgIR4MCQsgFCAQoSEeDAgLIBAgFKEhHgwHCyAQmiAUoSEeDAYLIA8gFKAhHgwFCyAPIBShIR4MBAsg"
			+ "D5ogFKEhHgwDCyAQIA+gIR4MAgsgFCAPoSEeDAELIA8gEKEhHgsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAAgASAaQQFqQf8BcWpqQRhqLQAAQQ9x"
			+ "DhAKDAECAwQFBgcLCAkKCwwACgsgD5ogFKEhHwwMCyATIA+hIR8MCwsgE5ogD6EhHwwKCyATIBSgIR8MCQsgFCAToSEfDAgLIBMgFKEhHwwHCyATmiAUoSEf"
			+ "DAYLIA8gFKAhHwwFCyAPIBShIR8MBAsgD5ogFKEhHwwDCyATIA+gIR8MAgsgFCAPoSEfDAELIA8gE6EhHwsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJA"
			+ "IAAgASAXQQFqQf8BcWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgEpogFKEhIAwMCyAQIBKhISAMCwsgEJogEqEhIAwKCyAQIBSgISAMCQsgFCAQ"
			+ "oSEgDAgLIBAgFKEhIAwHCyAQmiAUoSEgDAYLIBIgFKAhIAwFCyASIBShISAMBAsgEpogFKEhIAwDCyAQIBKgISAMAgsgFCASoSEgDAELIBIgEKEhIAsCQAJA"
			+ "AkACQAJAAkACQAJAAkACQAJAAkACQAJAIAAgASAYQQFqQf8BcWpqQRhqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgEpogFKEhEgwMCyATIBKhIRIMCwsg"
			+ "E5ogEqEhEgwKCyATIBSgIRIMCQsgFCAToSESDAgLIBMgFKEhEgwHCyATmiAUoSESDAYLIBIgFKAhEgwFCyASIBShIRIMBAsgEpogFKEhEgwDCyATIBKgIRIM"
			+ "AgsgFCASoSESDAELIBIgE6EhEgsgDSAHQcACaisDACAOIBUgECAQIBCioiAQIBBEAAAAAAAAGECiRAAAAAAAAC7AoKJEAAAAAAAAJECgoiIQIBsgFaGioCIT"
			+ "IA8gDyAPoqIgDyAPRAAAAAAAABhAokQAAAAAAAAuwKCiRAAAAAAAACRAoKIiDyAcIBAgHSAcoaKgIBOhoqAiEyARIBEgEaKiIBEgEUQAAAAAAAAYQKJEAAAA"
			+ "AAAALsCgokQAAAAAAAAkQKCiIB4gECAfIB6hoqAiESAPICAgECASICChoqAgEaGioCAToaKgoqKgIQ0gAUGwAmohAQwACwsgAkEIaiAFIAYgCCAGahCAgICA"
			+ "ACAKIAArAwgiD6IhISALIA+iIQsgDCAPoiEMRAAAAAAAAAAAIQ4gAigCDCEYIAIoAgghAQJAA0AgGEUNASABQZgCaisDACEbIAwgAUGgAmorAwAiD6IiEEQA"
			+ "AAAAAABgPqJEAAAAAAAA4D+gEIqAgIAAIREgCyAPoiISRAAAAAAAAGA+okQAAAAAAADgP6AQioCAgAAhEyAhIA+iIhREAAAAAAAAYD6iRAAAAAAAAOA/oBCK"
			+ "gICAACEVIBAgEUQAAAAAAACAQaKhIAFBgAJqKwMAoCEPIA8gDxCKgICAAPwCIha3oSEQIBIgE0QAAAAAAACAQaKhIAFBiAJqKwMAoCEPIA8gDxCKgICAAPwC"
			+ "Ihe3oSEPIBQgFUQAAAAAAACAQaKhIAFBkAJqKwMAoCERIBEgERCKgICAAPwCIge3oSERIAEgFyABIBZBAWpB/wFxai0AAGoiGUH/AXFqLQAAIRogASAXIAEg"
			+ "FkH/AXFqLQAAaiIWQQFqQf8BcWohFyABIBlBAWpB/wFxaiEZAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQCABIAcgASAWQf8BcWotAABqIhZB/wFxai0A"
			+ "AEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIA+aIBGhIRUMDAsgECAPoSEVDAsLIBCaIA+hIRUMCgsgECARoCEVDAkLIBEgEKEhFQwICyAQIBGhIRUMBwsgEJog"
			+ "EaEhFQwGCyAPIBGgIRUMBQsgDyARoSEVDAQLIA+aIBGhIRUMAwsgECAPoCEVDAILIBEgD6EhFQwBCyAPIBChIRULIBctAAAhFyAZLQAAIRkgEEQAAAAAAADw"
			+ "v6AhEwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgASAHIBpqIhpB/wFxai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIA+aIBGhIR0MDAsgEyAPoSEd"
			+ "DAsLIBOaIA+hIR0MCgsgEyARoCEdDAkLIBEgE6EhHQwICyATIBGhIR0MBwsgE5ogEaEhHQwGCyAPIBGgIR0MBQsgDyARoSEdDAQLIA+aIBGhIR0MAwsgEyAP"
			+ "oCEdDAILIBEgD6EhHQwBCyAPIBOhIR0LIA9EAAAAAAAA8L+gIRICQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAEgByAXaiIXQf8BcWotAABBD3EOEAoM"
			+ "AQIDBAUGBwsICQoLDAAKCyASmiARoSEcDAwLIBAgEqEhHAwLCyAQmiASoSEcDAoLIBAgEaAhHAwJCyARIBChIRwMCAsgECARoSEcDAcLIBCaIBGhIRwMBgsg"
			+ "EiARoCEcDAULIBIgEaEhHAwECyASmiARoSEcDAMLIBAgEqAhHAwCCyARIBKhIRwMAQsgEiAQoSEcCwJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAgASAH"
			+ "IBlqIgdB/wFxai0AAEEPcQ4QCgwBAgMEBQYHCwgJCgsMAAoLIBKaIBGhIR8MDAsgEyASoSEfDAsLIBOaIBKhIR8MCgsgEyARoCEfDAkLIBEgE6EhHwwICyAT"
			+ "IBGhIR8MBwsgE5ogEaEhHwwGCyASIBGgIR8MBQsgEiARoSEfDAQLIBKaIBGhIR8MAwsgEyASoCEfDAILIBEgEqEhHwwBCyASIBOhIR8LIBFEAAAAAAAA8L+g"
			+ "IRQCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAEgFkEBakH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgD5ogFKEhHgwMCyAQIA+hIR4MCwsg"
			+ "EJogD6EhHgwKCyAQIBSgIR4MCQsgFCAQoSEeDAgLIBAgFKEhHgwHCyAQmiAUoSEeDAYLIA8gFKAhHgwFCyAPIBShIR4MBAsgD5ogFKEhHgwDCyAQIA+gIR4M"
			+ "AgsgFCAPoSEeDAELIA8gEKEhHgsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAEgGkEBakH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgD5og"
			+ "FKEhCgwMCyATIA+hIQoMCwsgE5ogD6EhCgwKCyATIBSgIQoMCQsgFCAToSEKDAgLIBMgFKEhCgwHCyATmiAUoSEKDAYLIA8gFKAhCgwFCyAPIBShIQoMBAsg"
			+ "D5ogFKEhCgwDCyATIA+gIQoMAgsgFCAPoSEKDAELIA8gE6EhCgsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAEgF0EBakH/AXFqLQAAQQ9xDhAKDAEC"
			+ "AwQFBgcLCAkKCwwACgsgEpogFKEhIAwMCyAQIBKhISAMCwsgEJogEqEhIAwKCyAQIBSgISAMCQsgFCAQoSEgDAgLIBAgFKEhIAwHCyAQmiAUoSEgDAYLIBIg"
			+ "FKAhIAwFCyASIBShISAMBAsgEpogFKEhIAwDCyAQIBKgISAMAgsgFCASoSEgDAELIBIgEKEhIAsCQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAIAEgB0EB"
			+ "akH/AXFqLQAAQQ9xDhAKDAECAwQFBgcLCAkKCwwACgsgEpogFKEhEgwMCyATIBKhIRIMCwsgE5ogEqEhEgwKCyATIBSgIRIMCQsgFCAToSESDAgLIBMgFKEh"
			+ "EgwHCyATmiAUoSESDAYLIBIgFKAhEgwFCyASIBShIRIMBAsgEpogFKEhEgwDCyATIBKgIRIMAgsgFCASoSESDAELIBIgE6EhEgsgDiABQagCaisDACAbIBUg"
			+ "ECAQIBCioiAQIBBEAAAAAAAAGECiRAAAAAAAAC7AoKJEAAAAAAAAJECgoiIQIB0gFaGioCITIA8gDyAPoqIgDyAPRAAAAAAAABhAokQAAAAAAAAuwKCiRAAA"
			+ "AAAAACRAoKIiDyAcIBAgHyAcoaKgIBOhoqAiEyARIBEgEaKiIBEgEUQAAAAAAAAYQKJEAAAAAAAALsCgokQAAAAAAAAkQKCiIB4gECAKIB6hoqAiESAPICAg"
			+ "ECASICChoqAgEaGioCAToaKgoqKgIQ4gGEF/aiEYIAFBsAJqIQEMAAsLIANBA3QgDSAOoCAAKwMAojkDgIDAgAAgA0EBaiEDDAALCyACQRBqJICAgIAAC5oB"
			+ "BAF+AX8BfAJ+AkAgAL0iAUI0iKdB/w9xIgJBsghNDQAgAA8LAkACQCACQf4HSw0ARAAAAAAAAAAAIQMgAUJ/VQ0BIABEAAAAAAAA8L8gAEQAAAAAAAAAAGEb"
			+ "DwsgACEDQv////////8HIAJBgXhqrSIEiCIFIAGDUA0AIAFCP4cgBYMgAXxCgICAgICAgHggBIeDvyEDCyADCyQAIABBACAAQQBKGyIAQf8BIABB/wFIG0GY"
			+ "zABsQYCAzIAAagsIAEGAgMyAAAsHAANADAALCw==";

	private static int state = 0; // 0 = not yet loaded, 1 = available, 2 = failed/unsupported

	private PlatformNativeNoise() {
	}

	/** Lazily instantiate the kernel in this realm; true once it is ready to serve slots. */
	public static boolean available() {
		if (state == 0) {
			boolean ok;
			try {
				ok = nLoad(WASM_B64);
			} catch (Throwable t) {
				ok = false;
			}
			state = ok ? 1 : 2;
		}
		return state == 1;
	}

	/** Reserve a slot; -1 if the 256-slot pool is exhausted (caller falls back to Java). */
	public static int allocSlot() {
		return nAllocSlot();
	}

	public static void writeHeader(int slot, double valueFactor, double inputFactor, int firstCount, int secondCount) {
		nWriteHeader(slot, valueFactor, inputFactor, firstCount, secondCount);
	}

	/** perm256 = a 256-char string, char i = permutation byte i (0..255). */
	public static void writeOctave(int slot, int k, String perm256, double xo, double yo, double zo,
			double amplitude, double freqFactor, double valueFactor) {
		nWriteOctave(slot, k, perm256, xo, yo, zo, amplitude, freqFactor, valueFactor);
	}

	public static double noiseSlot(int slot, double x, double y, double z) {
		return nNoiseSlot(slot, x, y, z);
	}

	public static int maxBatchPoints() {
		return nMaxBatchPoints();
	}

	/** Evaluate packed xyz triples through one JS -> Rust boundary. */
	public static void noiseBatch(final int slot, final double[] packedCoordinates,
			final double[] output, final int count) {
		// WasmGC Java arrays are GC structs, not views over JS linear memory. The patched
		// TeaVM @JSByRef bridge therefore copies inputs and deliberately cannot write back
		// through an output parameter. Return a typed view of the Rust arena, explicitly
		// copy it into a Java array, then reuse the caller's bounded output scratch.
		double[] nativeOutput = nNoiseBatch(slot, packedCoordinates, count).copyToJavaArray();
		System.arraycopy(nativeOutput, 0, output, 0, count);
	}

	@JSBody(params = { "b64" }, script =
		"try{"
		+ "var bin=atob(b64);var n=bin.length;var bytes=new Uint8Array(n);"
		+ "for(var i=0;i<n;i++)bytes[i]=bin.charCodeAt(i)&0xFF;"
		+ "var inst=new WebAssembly.Instance(new WebAssembly.Module(bytes),{});"
		+ "var e=inst.exports;"
		+ "if(!e||!e.noise_slot||!e.noise_batch_slot||!e.max_batch_points||!e.io_ptr||!e.slot_ptr||!e.memory||!e.max_slots)return false;"
		+ "globalThis.__eagRustNoise={e:e,mem:e.memory,next:0,max:e.max_slots()|0};"
		+ "return true;"
		+ "}catch(err){return false;}")
	private static native boolean nLoad(String b64);

	@JSBody(params = {}, script =
		"var r=globalThis.__eagRustNoise;if(!r||r.next>=r.max)return -1;return r.next++;")
	private static native int nAllocSlot();

	@JSBody(params = { "slot", "valueFactor", "inputFactor", "c1", "c2" }, script =
		"var r=globalThis.__eagRustNoise;var dv=new DataView(r.mem.buffer);var b=r.e.slot_ptr(slot)|0;"
		+ "dv.setFloat64(b,valueFactor,true);dv.setFloat64(b+8,inputFactor,true);"
		+ "dv.setUint32(b+16,c1>>>0,true);dv.setUint32(b+20,c2>>>0,true);")
	private static native void nWriteHeader(int slot, double valueFactor, double inputFactor, int c1, int c2);

	@JSBody(params = { "slot", "k", "perm", "xo", "yo", "zo", "amp", "freq", "vf" }, script =
		"var r=globalThis.__eagRustNoise;var dv=new DataView(r.mem.buffer);var ob=(r.e.slot_ptr(slot)|0)+24+k*304;"
		+ "for(var i=0;i<256;i++)dv.setUint8(ob+i,perm.charCodeAt(i)&0xFF);"
		+ "dv.setFloat64(ob+256,xo,true);dv.setFloat64(ob+264,yo,true);dv.setFloat64(ob+272,zo,true);"
		+ "dv.setFloat64(ob+280,amp,true);dv.setFloat64(ob+288,freq,true);dv.setFloat64(ob+296,vf,true);")
	private static native void nWriteOctave(int slot, int k, String perm, double xo, double yo, double zo,
			double amp, double freq, double vf);

	@JSBody(params = { "slot", "x", "y", "z" }, script =
		"return globalThis.__eagRustNoise.e.noise_slot(slot,x,y,z);")
	private static native double nNoiseSlot(int slot, double x, double y, double z);

	@JSBody(params = {}, script =
		"return globalThis.__eagRustNoise.e.max_batch_points()|0;")
	private static native int nMaxBatchPoints();

	@JSBody(params = { "slot", "coordinates", "count" }, script =
		"var r=globalThis.__eagRustNoise;var n=count|0;var p=r.e.io_ptr()|0;"
		+ "new Float64Array(r.mem.buffer,p,n*3).set(coordinates.subarray(0,n*3));"
		+ "r.e.noise_batch_slot(slot|0,n);"
		+ "return new Float64Array(r.mem.buffer,p,n);")
	private static native Float64Array nNoiseBatch(int slot, @JSByRef double[] coordinates, int count);

}
