package net.lax1dude.eaglercraft.v1_8.profile;

import net.minecraft.client.gui.components.Button;
import net.minecraft.client.gui.components.StringWidget;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;

/**
 * 26.2 port of upstream profile/GuiScreenDefaultUsernameNote: warns when the
 * profile still uses an auto-generated username (upstream lang keys
 * eaglercraft.defaultUsernameDetected.*).
 */
public class EaglerDefaultUsernameNoteScreen extends Screen {

	private final Screen profileScreen;
	private final Screen continueTo;

	public EaglerDefaultUsernameNoteScreen(Screen profileScreen, Screen continueTo) {
		super(Component.translatableWithFallback("defaultUsernameDetected.title", "Default Username Detected"));
		this.profileScreen = profileScreen;
		this.continueTo = continueTo;
	}

	@Override
	protected void init() {
		int y = this.height / 6;
		addCenteredLine(this.title.copy().withStyle(s -> s.withColor(0xAAAAAA)), y + 10);
		addCenteredLine(Component.translatableWithFallback("defaultUsernameDetected.text0",
				"The username \"%s\" was auto-generated by Eaglercraft", EaglerProfile.getName()), y + 38);
		addCenteredLine(Component.translatableWithFallback("defaultUsernameDetected.text1",
				"It may already be taken on the largest servers"), y + 52);
		addCenteredLine(Component.translatableWithFallback("defaultUsernameDetected.text2",
				"Would you like to pick a different username instead?"), y + 66);

		this.addRenderableWidget(Button.builder(
				Component.translatableWithFallback("defaultUsernameDetected.changeUsername", "Change Username"),
				btn -> this.minecraft.gui.setScreen(profileScreen))
				.bounds(this.width / 2 - 100, y + 112, 200, 20).build());
		this.addRenderableWidget(Button.builder(
				Component.translatableWithFallback("defaultUsernameDetected.continueAnyway", "Continue Anyway"),
				btn -> this.minecraft.gui.setScreen(continueTo))
				.bounds(this.width / 2 - 100, y + 142, 200, 20).build());
		this.addRenderableWidget(Button.builder(
				Component.translatableWithFallback("defaultUsernameDetected.doNotShow", "Do not show again"),
				btn -> {
					EaglerProfile.setHideDefaultUsernameWarning(true);
					EaglerProfile.save();
					this.minecraft.gui.setScreen(continueTo);
				})
				.bounds(this.width / 2 - 100, y + 172, 200, 20).build());
	}

	private void addCenteredLine(Component text, int y) {
		int w = this.font.width(text);
		this.addRenderableWidget(new StringWidget(this.width / 2 - w / 2, y, w, 9, text, this.font));
	}

	@Override
	public boolean shouldCloseOnEsc() {
		return false;
	}

}
